package cards;

/**
 * Represents a playing card, with a value and a string representing the card.
 * The values can depend on the type of card used.
 *
 * For example, in a standard deck of cards there is a card named
 * the "Jack of Clubs" with a value of 10. In a game of Uno there
 * is a "Red Nine" card, with a value of 9.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public interface Card
{
    /**
     * Returns the value of the card
     * @return the value this card has, depending on the type of card
     */
    int getValue();

    /**
     * Returns the full card name.
     * @return the name of the card, for example "Ace of Spades" or
     * "10 of clubs", etc.
     */
    String getCardName();
}
